- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: openstack
    register: result

  - name: Debug Info
    debug:
      msg: "{{result.openstack_servers}}"
  
  # - name: Curl website
  #   uri:
  #     url: http://marathon.service.consul:8080/v2/apps/
  #     method: POST
  #     body: "{{ lookup('file','mesos-consul.json') }}"
  #     body_format: json
  #     headers:
  #       Content-Type: "application/json"
  #   loop: "{{result.openstack_servers}}"


  # - name: Fail if 'Ansible has done its job' is not in the page content
  #   fail:
  #   when: "'Ansible has done its job' not in webpage.results[0].content"
  #   tags:
  #     - osp.smoke
