---
- name: install "{{ payload }}"
  yum:
    name: "{{ payload }}"
    state: latest

- name: enable "{{ payload }}"
  service:
    name: "{{ payload }}"
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: restart "{{ payload }}"
  service:
    name: "{{ payload }}"
    state: restarted