---
# tasks file for osp.servers
- name: Create instances
  os_server:
    cloud: openstack
    name: "{{ item.0.name }}"
    image: "{{ item.0.image }}"
    key_name: "{{ item.0.key_name }}"
    flavor: "{{ item.0.flavor }}"
    security_groups: "{{ item.0.security_group }}"
    nics:
      - net-name: int_network
    meta: "{{ item.1 }}"
    userdata: |
      #!/bin/bash 
      echo "{{ lookup('file', 'openstack.pub') }}" >> /home/cloud-user/.ssh/authorized_keys
      curl -o /etc/yum.repos.d/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
  with_subelements:
    - "{{ osp_servers }}"
    - meta

- name: Add floating IP to instance
  os_floating_ip:
    cloud: openstack
    state: "{{ item.value.state }}"
    reuse: yes
    server: "{{ item.value.name }}"
    network: ext_network
    wait: true
    timeout: 200
  with_dict: "{{ osp_servers }}"
