---
- name: install pgsql
  yum:
    name: postgresql-server
    state: latest

- name: enable pgsql
  service:
    name: postgresql.service
    enabled: yes

- name: Check database initialization
  command: postgresql-check-db-dir  /var/lib/pgsql/data
  register: check_db_output
  changed_when: check_db_output == 1
  ignore_errors: yes
  
- name: initilize postgres
  shell: postgresql-setup initdb
  when: check_db_output.rc != 0

- name: start pgsql
  service:
    name: postgresql.service
    state: started